services:
  docs:
    image: livechat_local_docs
    container_name: livechat_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./livechat:/app/livechat:z
    ports:
      - '9000:9000'
    command: /start-docs
